version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - backend:/app/backend
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    volumes:
      - frontend:/app/frontend
    ports:
      - '3001:3001'

  nginx:
      image: nginx:1.25.1
      ports:
        - '80:80'
        - '443:443'
        - '8443:8443'
      volumes:
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/certs:/etc/nginx/certs/
      depends_on:
        - backend
        - frontend
        
volumes:
    backend:
    frontend: