import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { hola } from 'datamex-helpers';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [info, setInfo] = useState<string>('INICIAL')

  useEffect(()=>{
    const fetchData = async () => {
      try{
          const response = await fetch('https://localhost:8443/api');
          const data = await response.json();
          console.log(data)
          setInfo(data?.message || 'INFO')
      } catch(error) {
          console.log(error)
      }
    };
    fetchData();
  },[])

  const hi = hola();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{ hi }</h1>
        {info}
      </main>
    </>
  )
}
